# docker-compose.macos.yml
# macOS-specific services (excludes WhisperLive - uses native Whisper.cpp instead)

services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: kokoro
    ports:
      - "5001:8880"
    volumes:
      - kokoro_models:/models
    environment:
      - MODEL_PATH=/models
      - DEFAULT_VOICE=af_bella
      - DEVICE=cpu
    networks:
      - maestrocat-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - maestrocat-network
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

networks:
  maestrocat-network:
    driver: bridge

volumes:
  kokoro_models:
  ollama_data: