# config/basic_assistant.yaml
vad:
  energy_threshold: 0.5
  min_speech_ms: 250
  pause_ms: 800

llm:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

tts:
  voice_id: "21m00Tcm4TlvDq8ikWAM"
  stability: 0.75
  similarity_boost: 0.75

interruption:
  threshold: 0.2
  ack_delay: 0.05

modules:
  voice_recognition:
    enabled: false
  memory:
    enabled: false