# MaestroCat Configuration
vad:
  energy_threshold: 0.5
  min_speech_ms: 250
  pause_ms: 800

stt:
  host: "localhost"
  port: 9090
  language: "en"
  translate: false
  model: "small"
  use_vad: true

llm:
  base_url: "http://localhost:11434"
  model: "llama3.2:3b"
  temperature: 0.7
  max_tokens: 1000
  top_p: 0.9
  top_k: 40
  system_prompt: |
    You are a helpful AI assistant in a voice conversation.
    Keep responses concise and conversational.
    If interrupted, acknowledge it naturally.

tts:
  base_url: "http://localhost:5000"
  voice: "af_bella"
  speed: 1.0
  sample_rate: 16000

interruption:
  threshold: 0.2
  ack_delay: 0.05

modules:
  voice_recognition:
    enabled: false
    model: "speechbrain/spkrec-ecapa-voxceleb"
  memory:
    enabled: false
    max_history: 100
